### ISSUE TITLE
Replay2 or Relax2

### ISSUE THREAD

**Issue by TrueRou** [luis10barbo/python-gosu-pp#1]
![Snipaste_2022-04-09_20-23-51](https://user-images.githubusercontent.com/30361160/162574026-c6b3ca22-d5c7-4fb9-b558-ca0ed3a2c9b0.png)
Do you mean Relax2 ?

**Comment by luisnunmello** [comment]
This is my first issue, so bare with me if i do something wrong

Yeah i meant Relax2, Started using a map at the conversion to minimize errors like this
